# Generated by Django 4.2.6 on 2023-11-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("P_name", models.CharField(max_length=100)),
                ("P_Qty", models.IntegerField()),
                ("P_Price", models.FloatField(max_length=15)),
                (
                    "CATAGORY_CHOICES",
                    models.CharField(
                        choices=[("M", "Mens"), ("W", "Womens"), ("A", "All")],
                        default="A",
                        max_length=1,
                    ),
                ),
                (
                    "P_Image",
                    models.ImageField(blank=True, null=True, upload_to="image"),
                ),
                (
                    "R1_Image",
                    models.ImageField(blank=True, null=True, upload_to="image"),
                ),
                (
                    "R2_Image",
                    models.ImageField(blank=True, null=True, upload_to="image"),
                ),
                ("P_Desc", models.CharField(max_length=1000)),
            ],
        ),
    ]
