# Generated by Django 4.2.6 on 2023-11-12 15:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productitem",
            name="R1_Image",
        ),
        migrations.RemoveField(
            model_name="productitem",
            name="R2_Image",
        ),
    ]
