# Generated by Django 4.2.6 on 2023-11-20 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="product_id",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="cart",
            old_name="user_id",
            new_name="user",
        ),
    ]
